export default [
    {
        title: "All Coders",
        date: "22 May, 2024",
        time: "23:18 AM",
        startup: "EcoTrack",
        image: "/images/all_coders.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, esse, saepe!",
        user: "John Doe",
        ico: "/images/lapchip.jpg",
        comments: "23",
        likes: "22",
        shares: "12",
    },
    {
        title: "All Coders",
        date: "22 May, 2024",
        time: "23:18 AM",
        startup: "EcoTrack",
        image: "/images/all_coders.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, esse, saepe!",
        user: "John Doe",
        ico: "/images/lapchip.jpg",
        comments: "23",
        likes: "22",
        shares: "12",
    },
    {
        title: "All Coders",
        date: "22 May, 2024",
        time: "23:18 AM",
        startup: "EcoTrack",
        image: "/images/all_coders.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, esse, saepe!",
        user: "John Doe",
        ico: "/images/lapchip.jpg",
        comments: "23",
        likes: "22",
        shares: "12",
    },
    {
        title: "All Coders",
        date: "22 May, 2024",
        time: "23:18 AM",
        startup: "EcoTrack",
        image: "/images/all_coders.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, esse, saepe!",
        user: "John Doe",
        ico: "/images/lapchip.jpg",
        comments: "23",
        likes: "22",
        shares: "12",
    }
];
